In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("final_data.csv")
df.head()

,Id,Name,Categories,Latitude,Longitude,Address,Zip Code,Price,Rating,Review Count,Url,Walk Score,First Review Date
0,ZlIUV5wDsUrQJ1AgANG47g,Casey's New Orleans Snowballs,"['icecream', 'foodtrucks']",30.312077,-97.714964,808 E 51st St,78751.0,$,4.5,275,https://www.yelp.com/biz/caseys-new-orleans-sn...,70.0,2/23/2006
1,tHv6_4DKOV8sZnlvTrCN9Q,Rosita's Al Pastor,"['mexican', 'foodtrucks']",30.241899,-97.728518,1911 E Riverside Dr,78798.0,$,4.0,319,https://www.yelp.com/biz/rositas-al-pastor-aus...,70.0,2/23/2006
2,QjxEOAEqJkuCSmpBB2ZlgQ,Kebabalicious,"['turkish', 'foodtrucks']",30.267926,-97.738495,NaN,78704.0,$,4.5,313,https://www.yelp.com/biz/kebabalicious-austin-...,70.0,2/23/2006
3,bsh0QPcNL2BrcuCtCl8Qzw,Sno-Beach,"['shavedice', 'foodtrucks']",30.264573,-97.763282,412 Sterzing St,78704.0,$,4.5,207,https://www.yelp.com/biz/sno-beach-austin-4?ad...,72.0,5/11/2007
4,jq8h5wnIfL6bHS8UMcDNNQ,Hot Dog King,"['hotdog', 'foodtrucks']",30.268350,-97.736520,8th St & Red River St,78742.0,$,4.5,47,https://www.yelp.com/biz/hot-dog-king-austin?a...,90.0,9/10/2007

In [7]:
df1 = df.copy()
def cat1(categories):
    cat1 = categories.split("'")[1]
    if cat1 != "foodtrucks":
        return cat1
df1["Category"] = df1["Categories"].map(cat1)

In [9]:
df2 = df.copy()
def cat2(categories):
    try:
        cat2 = categories.split("'")[3]
    except:
        cat2 = None
    if cat2 != "foodtrucks":
        return cat2
df2["Category"] = df2["Categories"].map(cat2)

In [10]:
df3 = df.copy()
def cat3(categories):
    try:
        cat3 = categories.split("'")[5]
    except:
        cat3 = None
    if cat3 != "foodtrucks":
        return cat3
df3["Category"] = df3["Categories"].map(cat3)

In [12]:
df_cleaned = pd.concat([df1, df2, df3])
df_cleaned.head()

,Id,Name,Categories,Latitude,Longitude,Address,Zip Code,Price,Rating,Review Count,Url,Walk Score,First Review Date,Category
0,ZlIUV5wDsUrQJ1AgANG47g,Casey's New Orleans Snowballs,"['icecream', 'foodtrucks']",30.312077,-97.714964,808 E 51st St,78751.0,$,4.5,275,https://www.yelp.com/biz/caseys-new-orleans-sn...,70.0,2/23/2006,icecream
1,tHv6_4DKOV8sZnlvTrCN9Q,Rosita's Al Pastor,"['mexican', 'foodtrucks']",30.241899,-97.728518,1911 E Riverside Dr,78798.0,$,4.0,319,https://www.yelp.com/biz/rositas-al-pastor-aus...,70.0,2/23/2006,mexican
2,QjxEOAEqJkuCSmpBB2ZlgQ,Kebabalicious,"['turkish', 'foodtrucks']",30.267926,-97.738495,NaN,78704.0,$,4.5,313,https://www.yelp.com/biz/kebabalicious-austin-...,70.0,2/23/2006,turkish
3,bsh0QPcNL2BrcuCtCl8Qzw,Sno-Beach,"['shavedice', 'foodtrucks']",30.264573,-97.763282,412 Sterzing St,78704.0,$,4.5,207,https://www.yelp.com/biz/sno-beach-austin-4?ad...,72.0,5/11/2007,shavedice
4,jq8h5wnIfL6bHS8UMcDNNQ,Hot Dog King,"['hotdog', 'foodtrucks']",30.268350,-97.736520,8th St & Red River St,78742.0,$,4.5,47,https://www.yelp.com/biz/hot-dog-king-austin?a...,90.0,9/10/2007,hotdog

In [13]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1890 entries, 0 to 629
Data columns (total 14 columns):
Id                   1890 non-null object
Name                 1890 non-null object
Categories           1890 non-null object
Latitude             1887 non-null float64
Longitude            1887 non-null float64
Address              1689 non-null object
Zip Code             1872 non-null float64
Price                1332 non-null object
Rating               1890 non-null float64
Review Count         1890 non-null int64
Url                  1890 non-null object
Walk Score           1887 non-null float64
First Review Date    1890 non-null object
Category             718 non-null object
dtypes: float64(5), int64(1), object(8)
memory usage: 221.5+ KB

In [15]:
df_cleaned.to_csv("cat_data.csv", index=False)